// Kat is a weightlifter.
print("K      K  PPPPPP")
print("K     K   P     P")
print("K    K    P      P")
print("K   K     P       P")
print("K  K      P      P")
print("K K       P     P")
print("K K       PPPPPP")
print("K  K      P")
print("K   K     P")
print("K    K    P")
print("K     K   P")
print("K      K  P")
print("K       K P")